---

- name: "Upgrade to pve6.2"
  ansible.builtin.apt:
    name: pve-kernel-6.2
    state: present
  when: "pve_reboot_on_kernel_update | bool"
  register: _pve_kernel_62

- name: "Reboot for kernel update"
  reboot:
    msg: "PVE kernel update detected by Ansible"
    pre_reboot_delay: "{{ pve_reboot_on_kernel_update_delay }}"
    post_reboot_delay: "{{ pve_reboot_on_kernel_update_delay }}"
  throttle: "{{ pve_cluster_enabled | bool }}"
  when:
    - "_pve_kernel_62.changed"
    
- name: "Check for kernel update"
  collect_kernel_info:
    lookup_packages: false
  register: _pve_kernel_update
  when: "pve_reboot_on_kernel_update | bool"

- name: "Collect kernel package information"
  collect_kernel_info:
  register: _pve_kernel

- name: "Remove old Debian/PVE kernels"
  apt:
    name: "{{ ['linux-image-amd64'] + _pve_kernel.old_packages }}"
    state: absent
    purge: yes
  when:
    - "pve_remove_old_kernels | bool"
